repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
    -   id: double-quote-string-fixer
    -   id: end-of-file-fixer
    -   id: fix-encoding-pragma
    -   id: mixed-line-ending
    -   id: trailing-whitespace

-   repo: https://github.com/pre-commit/mirrors-yapf
    rev: v0.30.0
    hooks:
    -   id: yapf
        name: yapf
        types: [python]
        args: ['-i']

-   repo: https://github.com/PyCQA/pylint
    rev: pylint-2.5.2
    hooks:
    -   id: pylint
        language: system
        args: [
            '--max-line-length=120',
            '--disable=import-outside-toplevel'
        ]

-   repo: https://github.com/PyCQA/pydocstyle
    rev: 5.0.2
    hooks:
    -   id: pydocstyle
        args: ['--ignore=D104,D203,D213']
